apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: server
  name: server
  namespace: pix-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: server
    spec:
      containers:
      - image: docker.io/library/pix-challenge-server:latest
        name: pix-challenge-server-msx8h
        resources: {}
        imagePullPolicy: Never
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: pix-challenge
spec:
  selector:
    app: server
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 5000
  type: ClusterIP